HotelManagementEntity/HotelManagementEntity/Models/CheckIn.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementEntity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CheckIn
    {
        
        public int GuestId { get; set; }
        [Required]
        public int RoomId { get; set; }
        public int RoomType { get; set; }
         [Required]
        public string GuestName { get; set; }
         [Required]
        public string Address { get; set; }
         [Required]
        [Range(0000000000,9999999999,ErrorMessage="Should be 10 digits")]
        public int Contact { get; set; }
         [Required]
         [Range(1, 999, ErrorMessage = "Quantity cannot be less than 1")]
        public int Quantity { get; set; }
         [Required]
         [DataType(DataType.Date)]
        public System.DateTime CheckInTime { get; set; }
        public string Status { get; set; }
    }
}

HotelManagementEntity/HotelManagementEntity/Controllers/CheckInController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HotelManagementEntity.Models;

namespace HotelManagementEntity.Controllers
{
    public class CheckInController : Controller
    {
        private HotelEntities7 db = new HotelEntities7();

        // GET: /CheckIn/
        public ActionResult Index(string name)
        {
            if (name == null)
            {
                return View(db.CheckIns.ToList());

            }
            return View(db.CheckIns.Where(c => c.GuestName == name).ToList());

        }

        // GET: /CheckIn/Details/5
        public ActionResult Details(int? id)
        {
            CheckIn checkin = null;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            foreach(var x in db.CheckIns)
            {
                if(x.GuestId==id)
                {
                    checkin = x;
                }
            }
            if (checkin == null)
            {
                return HttpNotFound();
            }
            return View(checkin);
        }

        // GET: /CheckIn/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /CheckIn/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CheckIn checkin)
        {
            if (ModelState.IsValid)
            {
                //check if rooms are available , then check in

                //find Room
                try
                {
                    var currentRoom = db.Rooms.Find(checkin.RoomId);
                    ViewBag.RoomsAvailable =  currentRoom.NoOfRooms + " rooms available";
                     
                    //check if room is available
                    if (currentRoom.NoOfRooms >= checkin.Quantity)
                    {
                        try
                        {
                            checkin.Status = "CheckedIn";
                            db.CheckIns.Add(checkin);
                            currentRoom.NoOfRooms -= checkin.Quantity;
                        
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                        catch (Exception e)
                        {
                            ViewBag.CannotAddRoom = e;
                        }
                       
                    }
                    return View();
               
                }
                catch(Exception e)
                {
                    ViewBag.CannotFindRoom = e;
                }
               
            }

            return View(checkin);
        }

        // GET: /CheckIn/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckIn checkin = db.CheckIns.Find(id);
            if (checkin == null)
            {
                return HttpNotFound();
            }
            return View(checkin);
        }

        // POST: /CheckIn/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="RoomId,RoomType,GuestName,Address,Contact,Quantity,CheckInTime,Status")] CheckIn checkin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(checkin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(checkin);
        }

        // GET: /CheckIn/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckIn checkin = db.CheckIns.Find(id);
            if (checkin == null)
            {
                return HttpNotFound();
            }
            return View(checkin);
        }

        // POST: /CheckIn/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                 //find checkin with given id
                CheckIn checkin = db.CheckIns.Find(id);
                List<CheckIn> guestList = new List<CheckIn>();
                guestList = db.CheckIns.ToList();
                int guestroomid = 0;
                foreach(var x in guestList)
                {
                    if(x.GuestId==id)
                    {
                        guestroomid = x.RoomId;
                    }
                }
                //Find current room and add back the released rooms by guest
                Room room = db.Rooms.Find(guestroomid);

                if (checkin.Status.Contains("CheckedIn")) //if checked in , no need to vacant the rooms
                {
                    room.NoOfRooms += checkin.Quantity;
                }
                //remove the guest and release the room
                //db.CheckIns.Remove(checkin);
                checkin.Status = "CheckedOut";
                //save the changes to db
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View(e);
            }
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
       
    }
}

HotelManagementEntity/HotelManagementEntity/Views/CheckIn/Create.cshtml
@model HotelManagementEntity.Models.CheckIn

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@{
    var RoomTypeList = new List<SelectListItem>(){
        new SelectListItem(){Value="1",Text="Standard"},
        new SelectListItem(){Value="2",Text="Deluxe"},
        new SelectListItem(){Value="3",Text="Supreme"}
    };
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheckIn</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomId)
                @Html.ValidationMessageFor(model => model.RoomId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoomType, RoomTypeList)
                @Html.ValidationMessageFor(model => model.RoomType)
            </div>
            <p>@ViewBag.RoomsAvailable</p>

        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.GuestName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestName)
                @Html.ValidationMessageFor(model => model.GuestName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact)
                @Html.ValidationMessageFor(model => model.Contact)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckInTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckInTime)
                @Html.ValidationMessageFor(model => model.CheckInTime)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HotelManagementEntity/HotelManagementEntity/Views/CheckIn/Delete.cshtml
@model HotelManagementEntity.Models.CheckIn

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to check out?</h3>
<div>
    <h4>CheckIn</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuestName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuestName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HotelManagementEntity/HotelManagementEntity/Views/CheckIn/Details.cshtml
@model HotelManagementEntity.Models.CheckIn

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CheckIn</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuestName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuestName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id =Model.GuestId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HotelManagementEntity/HotelManagementEntity/Views/CheckIn/Edit.cshtml
@model HotelManagementEntity.Models.CheckIn

@{
    ViewBag.Title = "Edit";
}


@{
    var RoomTypeList = new List<SelectListItem>(){
        new SelectListItem(){Value="1",Text="Standard"},
        new SelectListItem(){Value="2",Text="Deluxe"},
        new SelectListItem(){Value="3",Text="Supreme"}
    };
}
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheckIn</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.RoomId)


        <div class="form-group">
            @Html.LabelFor(model => model.RoomType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoomType, RoomTypeList)
                @Html.ValidationMessageFor(model => model.RoomType)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.GuestName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestName)
                @Html.ValidationMessageFor(model => model.GuestName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact)
                @Html.ValidationMessageFor(model => model.Contact)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckInTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckInTime)
                @Html.ValidationMessageFor(model => model.CheckInTime)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HotelManagementEntity/HotelManagementEntity/Views/CheckIn/Index.cshtml
@model IEnumerable<HotelManagementEntity.Models.CheckIn>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using(Html.BeginForm("Index", "CheckIn", FormMethod.Get)) {
    <div class="form-group">
        <input type="text" name="name" placeholder="Enter name here" />
    </div>
    <input type="submit" value="Search"/>
}

<table class="table">
    <tr> 
        <th>
            @Html.DisplayNameFor(model => model.RoomType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GuestName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </th>
        <th>@Html.DisplayNameFor(model => model.Status)</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RoomType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GuestName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contact)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckInTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.GuestId }) |
            @Html.ActionLink("Checkout", "Delete", new { id=item.GuestId }) |
           


        </td>
    </tr>
}

</table>